name: Container

on: workflow_dispatch

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    env:
      INVOKEAI_ROOT: "~/invokeai"
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: mkdir $INVOKEAI_ROOT
      - run: |
          cd $INVOKEAI_ROOT
          python -m venv .venv --prompt InvokeAI
      - run: source .venv/bin/activate
      - run: python -m pip install --upgrade pip
      - run: pip install InvokeAI --use-pep517 --extra-index-url https://download.pytorch.org/whl/cpu
      - run: deactivate && source .venv/bin/activate
      - run: invokeai-configure
      - run: invokeai