name: InvokeAI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  invokeai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python -m venv .venv --prompt InvokeAI
      - run: source .venv/bin/activate
      - run: python -m pip install --upgrade pip
      - run: pip install InvokeAI --use-pep517 --extra-index-url https://download.pytorch.org/whl/cpu
      - run: deactivate && source .venv/bin/activate
      - run: invokeai-configure
      - run: invokeai